### PR TITLE
More 508 accessibility fixes

### LINKED ISSUE #88: Fix current accessibility issues, per review feedback
Per @nickbristow's overall review in https://github.com/18F/dotgov-dashboard/issues/73#issuecomment-101805279, here are the elements we need to fix:

- [x] Unique Page titles (about page, analytics)
- [ ] Associate "Show __ Entries" label with select box
- [x] For tables (https, analytics) add scope to column headers and row headers (first element)
- [x] Add visual focus when using keyboard to tabs (about, analytics, HTTPS)
- [x] Add skip nav link
- [ ] Add aria to pagination links on tables

### PR DESCRIPTION
**Pull request by juliaelman**
This pull request adds the final set for accessibility changes. Fixes #88.

### CODE REVIEW

File: assets/js/https/domains.js [hunk 1]
```diff
@@ -203,6 +203,16 @@ $(document).ready(function () {
         }
       ],
 
+      columnDefs: [
+        {
+          targets: 0,
+          cellType: "td",
+          createdCell: function (td) {
+            td.scope = "row";
```
Comment (konklone) [inline assets/js/https/domains.js]: What does this callback do?

**Comment by konklone** [comment]
Looks good to me!
